server:
  port: 9999
  servlet.context-path: /
cloud:
  aws:
    region:
      static: ap-southeast-1
    stack:
      auto: false
    credentials:
      accessKey: AKIA45AF3QVWFNIHGZOF
      secretKey: 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
application:
  bucket-name:
    public: cuongnh2k-bucket-public
    private: cuongnh2k-bucket-private
  email:
    username: 1
    password: 2
  jwt:
    secret-key: a3f52f3a-5d8f-4f80-bc97-8d51a9fc4c9c
    access-token-age: 3600000
    refresh-token-age: 31536000000
spring.datasource:
  url: jdbc:mysql://localhost:3306/COMMON?allowPublicKeyRetrieval=true&useSSL=false
  username: root
  password: 231020
