server:
  port: 9999
  servlet.context-path: /
cloud:
  aws:
    region:
      static: ap-southeast-1
    stack:
      auto: false
    credentials:
      accessKey: AKIAYVGDULSKVEWXTFGR
      secretKey: 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
application:
  bucket-name:
    public: space.cuongnh2k.s3.bucket.public
    private: space.cuongnh2k.s3.bucket.private
  email:
    username: cuongnh3@rikkeisoft.com
    password: qzbhybpogwafideq
  jwt:
    secret-key: a3f52f3a-5d8f-4f80-bc97-8d51a9fc4c9c
    access-token-age: 3600000
    refresh-token-age: 31536000000
spring.datasource:
  url: jdbc:mysql://localhost:3306/COMMON?allowPublicKeyRetrieval=true&useSSL=false
  username: root
  password: 231020
