server:
  port: 9999
  servlet.context-path: /
  ssl:
    key-store-type: PKCS12
    key-store: classpath:cuongnh2k.space/certificate.p12
    key-store-password: 8bf53b11-7b98-4052-a7ae-b5ce786556d0
    enabled: true
cloud:
  aws:
    region:
      static: ap-southeast-1
    stack:
      auto: false
    credentials:
      accessKey: AKIAYVGDULSKVEWXTFGR
      secretKey: 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
application:
  bucket-name:
    public: space.cuongnh2k.s3.bucket.public
    private: space.cuongnh2k.s3.bucket.private
  email:
    username: cuongnh3@rikkeisoft.com
    password: qzbhybpogwafideq
  jwt:
    secret-key: a3f52f3a-5d8f-4f80-bc97-8d51a9fc4c9c
    access-token-age: 3600000
    refresh-token-age: 31536000000
spring.datasource:
  url: jdbc:mysql://13.229.201.209:3306/COMMON?allowPublicKeyRetrieval=true&useSSL=false
  username: cuongnh2k
  password: 9c54b4b4-c87b-420d-8460-12e91a32e416
